name: CD
# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, deployment!
